name: Release

on:
  schedule:
  - cron: "25 */6 * * *"
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pre-Source
        run:  python src/misc.cpp
