name: Release

on:
  schedule:
    - cron: "25 */4 * * *"
  push:
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pre-Source
        run:  python src/misc.cpp
